/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DesignRouteImport } from './routes/design'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppActivitiesRouteImport } from './routes/_app.activities'
import { Route as AppCalendarsRouteImport } from './routes/_app.calendars'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AuthCompleteRouteImport } from './routes/auth.complete'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarsRoute = AppCalendarsRouteImport.update({
  id: '/calendars',
  path: '/calendars',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AuthCompleteRoute = AuthCompleteRouteImport.update({
  id: '/auth/complete',
  path: '/auth/complete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/design': typeof DesignRoute
  '/signin': typeof SigninRoute
  '/activities': typeof AppActivitiesRoute
  '/calendars': typeof AppCalendarsRoute
  '/settings': typeof AppSettingsRoute
  '/auth/complete': typeof AuthCompleteRoute
}
export interface FileRoutesByTo {
  '/design': typeof DesignRoute
  '/signin': typeof SigninRoute
  '/activities': typeof AppActivitiesRoute
  '/calendars': typeof AppCalendarsRoute
  '/settings': typeof AppSettingsRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/design': typeof DesignRoute
  '/signin': typeof SigninRoute
  '/_app/activities': typeof AppActivitiesRoute
  '/_app/calendars': typeof AppCalendarsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/signin'
    | '/activities'
    | '/calendars'
    | '/settings'
    | '/auth/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/design'
    | '/signin'
    | '/activities'
    | '/calendars'
    | '/settings'
    | '/auth/complete'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/design'
    | '/signin'
    | '/_app/activities'
    | '/_app/calendars'
    | '/_app/settings'
    | '/auth/complete'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DesignRoute: typeof DesignRoute
  SigninRoute: typeof SigninRoute
  AuthCompleteRoute: typeof AuthCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activities': {
      id: '/_app/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendars': {
      id: '/_app/calendars'
      path: '/calendars'
      fullPath: '/calendars'
      preLoaderRoute: typeof AppCalendarsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/complete': {
      id: '/auth/complete'
      path: '/auth/complete'
      fullPath: '/auth/complete'
      preLoaderRoute: typeof AuthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppActivitiesRoute: typeof AppActivitiesRoute
  AppCalendarsRoute: typeof AppCalendarsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesRoute: AppActivitiesRoute,
  AppCalendarsRoute: AppCalendarsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DesignRoute: DesignRoute,
  SigninRoute: SigninRoute,
  AuthCompleteRoute: AuthCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
