import { type AddonManifest, parseManifest } from "@wiseroutine/addons";

/**
 * The addons this app will serve, and the only ones it will.
 *
 * ## How something gets on this list
 *
 * A contributor opens a pull request against the addons repository with their
 * source. It is reviewed as source - which is the point of doing it this way
 * rather than through an upload form, where the thing under review would be a
 * bundle nobody can read. On merge, CI builds it, takes the sha256, signs that
 * with the release key and publishes both the bundle and an updated index.
 *
 * So this file is the *shape* of the index rather than its permanent home.
 * Today it is a constant, because there is one addon and it is ours. When CI
 * starts publishing, this becomes a read of what it published, and the entries
 * stop being written by hand. Nothing downstream changes: an entry is an entry.
 *
 * ## Why the server owns it at all
 *
 * The bundle could be fetched straight from wherever CI put it, and then there
 * would be no revoking it. An addon that turns out to be malicious after it was
 * approved has to stop being installable, and stop running where it already is,
 * without waiting for an app release. That is a list somebody controls, and it
 * is this one.
 */

export interface RegistryEntry {
  id: string;
  version: string;
  /** Where the bundle is. Relative today; a CDN URL once CI publishes. */
  bundleUrl: string;
  /** sha256 of the bundle, as published. Empty until CI signs. */
  bundleHash: string;
  manifest: AddonManifest;
  /**
   * Withdrawn after the fact.
   *
   * Separate from simply not being listed: an addon that is merely absent is
   * one the app has never heard of, and an addon that is `revoked` is one the
   * app must *stop running* where it is already installed. The difference is
   * the whole reason the app asks this server rather than a static file.
   */
  revoked?: boolean;
  /** Shown on the addon's card. Who to blame, and who to thank. */
  author: string;
}

/**
 * The app's own breathing pacer, listed like anything else.
 *
 * Deliberately not special-cased. It is installed, removed and re-installed
 * through exactly the path a community addon takes, which is the only way to
 * know that path works - a route only strangers' code travels is a route
 * nobody maintains.
 */
const BREATHING = {
  id: "wiseroutine.breathing",
  name: "Breathing",
  version: "1.0.0",
  description:
    "A circle paces your breathing for the whole slot - box, 4-7-8 or coherent.",
  capabilities: [{ kind: "ui:session" }],
  activityTypes: [
    {
      key: "pacer",
      name: "Breathing",
      blurb:
        "a circle paces your breathing for the whole slot - box, 4-7-8 or coherent",
      defaults: { sessionMinutes: 3, startPolicy: "manual" },
      ground: "dim",
      settings: [
        {
          key: "pattern",
          label: "Pattern",
          type: "select",
          default: "box 4-4-4-4",
          options: ["box 4-4-4-4", "4-7-8", "coherent 5-5"],
        },
      ],
    },
  ],
};

/**
 * Every entry, validated the same way the client will validate it.
 *
 * `parseManifest` runs here rather than being trusted: this file is edited by
 * hand today and generated by CI tomorrow, and a manifest that does not parse
 * would be an addon the client silently refuses to install with no clue why.
 * Better that the server refuses to list it.
 */
export function registry(): RegistryEntry[] {
  const entries: { raw: unknown; entry: Omit<RegistryEntry, "manifest"> }[] = [
    {
      raw: BREATHING,
      entry: {
        id: "wiseroutine.breathing",
        version: "1.0.0",
        // Bundled with the app rather than downloaded, so a relative path.
        // A community addon's is an absolute URL and nothing else differs.
        bundleUrl: "/addons/wiseroutine.breathing/addon.js",
        bundleHash: "",
        author: "Wise Routine",
      },
    },
  ];

  const listed: RegistryEntry[] = [];
  for (const { raw, entry } of entries) {
    const manifest = parseManifest(raw);
    if (!manifest || manifest.id !== entry.id) continue;
    listed.push({ ...entry, manifest });
  }
  return listed;
}

export const entryFor = (id: string): RegistryEntry | undefined =>
  registry().find((entry) => entry.id === id);
