#!/usr/bin/env node
/**
 * Build `apps/api/.dev.vars` from the two files that already hold the answers.
 *
 *   pnpm --filter @wiseroutine/api dev:vars
 *
 * Secrets come from `.env.dev`, vars from the `dev` environment in
 * `wrangler.jsonc`. Neither is retyped, which is the point: a hand-written
 * `.dev.vars` drifts from both, and a value invented to fill a gap is worse
 * than a missing one — it looks configured and behaves wrongly.
 *
 * Two rules decide what lands here:
 *
 *   - Vars already in the **top-level** block are skipped. That block is the
 *     local one, and `.dev.vars` overrides it — copying `APP_URL` or
 *     `TURSO_DIRECTORY_URL` from the deployed environment would point local
 *     development at deployed infrastructure.
 *   - Anything still holding a `REPLACE_WITH_…` placeholder is skipped, and
 *     said out loud. A placeholder is not a value.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { declared, PKG } from "./secrets-lib.mjs";

const WRANGLER = new URL("wrangler.jsonc", `file://${PKG}`);
const ENV_FILE = new URL(".env.dev", `file://${PKG}`);
const OUT = new URL(".dev.vars", `file://${PKG}`);

/** The `vars` object of one environment, brace-matched so a nested block
 *  cannot end the slice early. `null` scopes to the top-level block. */
function varsOf(text, env) {
  const scope =
    env === null
      ? text.slice(0, text.indexOf('"env": {'))
      : text.slice(text.indexOf(`"${env}": {`));

  const start = scope.indexOf('"vars": {');
  if (start === -1) return new Map();

  let depth = 0;
  let end = start;
  for (let i = scope.indexOf("{", start); i < scope.length; i++) {
    if (scope[i] === "{") depth++;
    else if (scope[i] === "}" && --depth === 0) {
      end = i;
      break;
    }
  }

  return new Map(
    [...scope.slice(start, end).matchAll(/"([A-Z_]+)":\s*"([^"]*)"/g)].map(
      (m) => [m[1], m[2]],
    ),
  );
}

function envFileValues() {
  const values = new Map();
  for (const line of readFileSync(ENV_FILE, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (trimmed === "" || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const value = trimmed
      .slice(eq + 1)
      .trim()
      .replace(/^(['"])(.*)\1$/s, "$2");
    if (value !== "") values.set(trimmed.slice(0, eq).trim(), value);
  }
  return values;
}

function main() {
  const text = readFileSync(WRANGLER, "utf8");
  const { names, prefix } = declared("dev");

  const local = varsOf(text, null);
  const deployed = varsOf(text, "dev");
  const secrets = envFileValues();

  const lines = [
    "# Generated by `pnpm --filter @wiseroutine/api dev:vars` — do not edit.",
    "# Secrets from .env.dev, vars from the dev environment in wrangler.jsonc.",
    "# Local-only and gitignored. Re-run after changing either source.",
    "",
    "# ── Secrets (.env.dev) ──",
  ];

  const skipped = [];
  for (const name of names) {
    const key = name.slice(prefix.length);
    const value = secrets.get(key);
    if (value === undefined) skipped.push(`${key} (not in .env.dev)`);
    else lines.push(`${key}=${value}`);
  }

  lines.push("", "# ── Vars (wrangler.jsonc, env.dev) ──");
  for (const [key, value] of deployed) {
    // The top-level block is the local one and .dev.vars overrides it.
    if (local.has(key)) continue;
    if (value.startsWith("REPLACE_WITH")) {
      skipped.push(`${key} (still a placeholder in wrangler.jsonc)`);
      continue;
    }
    lines.push(`${key}=${value}`);
  }
  lines.push("");

  writeFileSync(OUT, lines.join("\n"));

  const written = lines.filter((l) => /^[A-Z_]+=/.test(l)).length;
  console.log(`[dev-vars] wrote .dev.vars — ${written} values`);
  for (const s of skipped) console.log(`  skipped ${s}`);

  // The one combination that silently breaks sign-in.
  for (const key of ["RESEND_API_KEY", "RESEND_FROM"]) {
    if (!lines.some((l) => l.startsWith(`${key}=`))) {
      console.log(`\n[dev-vars] ${key} is not set — sign-in will fail.`);
    }
  }
}

main();
